export { default as LoginPage } from './LoginPage'
export { default as MainPage } from './MainPage'
export { default as RegisterPage } from './RegisterPage'
export { default as AddPage } from './AddPage'
export { default as EditPage } from './EditPage'
